# Generated by Django 4.1.2 on 2023-02-01 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookWithIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=255, verbose_name='ISBN: The International Standard Book Number')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('authors', models.ManyToManyField(related_name='books_w_index', to='demo_manager.author')),
            ],
            options={
                'verbose_name': 'book with index',
                'verbose_name_plural': 'books with index',
                'ordering': ['title'],
            },
        ),
    ]
