# Generated by Django 4.1.2 on 2023-03-28 17:03

import demo_manager.models.resize_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_manager', '0003_userbookstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', demo_manager.models.resize_image.ResizeImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
    ]
