# Generated by Django 4.1.2 on 2023-03-29 08:41

from django.db import migrations, models
import pictures.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_manager', '0003_userbookstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture_width', models.PositiveIntegerField(null=True)),
                ('picture_height', models.PositiveIntegerField(null=True)),
                ('picture', pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['JPEG'], grid_columns=12, height_field='picture_height', null=True, pixel_densities=[1, 2], upload_to='pictures', width_field='picture_width')),
                ('std_image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='path/to/img', variations={'large': (6000, 4000)})),
            ],
        ),
    ]
