# Generated by Django 4.1.2 on 2023-02-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_profile'),
        ('demo_manager', '0002_bookwithindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookStorage',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='book_storage', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('books', models.ManyToManyField(blank=True, to='demo_manager.bookwithindex')),
            ],
        ),
    ]
